export const UNIT_OPTIONS = [
  { value: 'UN', label: 'Unidade (UN)' },
  { value: 'PC', label: 'Peça (PC)' },
  { value: 'CX', label: 'Caixa (CX)' },
  { value: 'PT', label: 'Pacote (PT)' },
  { value: 'FD', label: 'Fardo (FD)' },
  { value: 'SC', label: 'Saco (SC)' },
  { value: 'LT', label: 'Litro (LT)' },
  { value: 'ML', label: 'Mililitro (ML)' },
  { value: 'KG', label: 'Quilograma (KG)' },
  { value: 'G', label: 'Grama (G)' },
  { value: 'MG', label: 'Miligrama (MG)' },
  { value: 'M', label: 'Metro (M)' },
  { value: 'CM', label: 'Centímetro (CM)' },
  { value: 'MM', label: 'Milímetro (MM)' },
  { value: 'M2', label: 'Metro quadrado (M²)' },
  { value: 'M3', label: 'Metro cúbico (M³)' },
  { value: 'PR', label: 'Par (PR)' },
  { value: 'JG', label: 'Jogo (JG)' },
  { value: 'CJ', label: 'Conjunto (CJ)' },
  { value: 'RL', label: 'Rolo (RL)' },
  { value: 'BD', label: 'Balde (BD)' },
  { value: 'FR', label: 'Frasco (FR)' },
  { value: 'TB', label: 'Tubo (TB)' },
];
